### ISSUE TITLE
Config struct member missing

### ISSUE THREAD

**Issue by mlctrez** [connornishijima/SensoryBridge#14]
It looks like CONFIG.WAVEFORM_NOISE_FLOOR was removed in the last commit
https://github.com/connornishijima/SensoryBridge/commit/dc1723ddd79ccc060c36c365b3708477bb5a626a#diff-571ceae728b009de16bdde2450c864bf6a7aeb69530b3b59158f28ccf3ef04b3

It's still referenced in 
https://github.com/connornishijima/SensoryBridge/blob/dc1723ddd79ccc060c36c365b3708477bb5a626a/SENSORY_BRIDGE_FIRMWARE/serial_menu.h#L153

**Comment by connornishijima** [comment]
Thank you Matt! *How embarrassing*, I'm not sure how I didn't catch that. As soon as 3.0.0 is done and out of beta, I've meaning to install CI workflows here like my Pixie Chroma repo. 😅

That `dump()` function in serial_menu.h is a bit bloated and hard to keep track of at this point, I wish there was a way for "Arduino C" to iterate over a struct and access a string value of each key's name in a `for` loop instead of the current brute force manual printing I'm doing, that could have avoided the issue. (Maybe ArduinoJSON lets me do that.)

Fixed in [182c288](https://github.com/connornishijima/SensoryBridge/commit/182c28834a68e85de550fb1a077a846eea175a5d), release re-issued as 3.0.0-beta4-bugfix. Enjoy the update!

**Comment by mlctrez** [comment]
"given enough eyeballs, all bugs are shallow"

Thanks for releasing 3.0, enjoying it very much. It does seem that the beta4 has a much lower gain ( if this is the right term ) and the music must be playing quite a bit louder for it to work.  Is there a configuration setting that can be used to adjust the sensitivity?  I've not been tracking in the updates how the sensitivity works, maybe I'm missing something.
