### ISSUE TITLE
Freezing with MicroDose on 4.1.0

### ISSUE THREAD

**Issue by andyshinn** [connornishijima/SensoryBridge#30]
The MicroDose looks pretty good. But after a couple hours the lighting on the Sensory Bridge freezes. Other functions still seem to be working (the sweet spot LEDs are moving and I can connect to the device over USB). When I change back to the mast and set the LED settings for the mast it doesn't freeze. Maybe a bug somewhere specific to the output for MicroDose?

![IMG_1358](https://github.com/connornishijima/SensoryBridge/assets/315485/ce4f7768-b0d6-4efb-8056-4079fe75b7e9)

**Comment by RWBRWB** [comment]
Same issue here with the Microdose. 

Exactly the same freezing of the LED's while the other functions look to be working and USB output to the chrome page still shows updated FPS numbers. 

The main mast works perfectly. 

Seems to bet an error with the dual 128 pixel output code. 

Looks great otherwise and looking forward to getting this bug found and fixed.

**Comment by RWBRWB** [comment]
> The MicroDose looks pretty good. But after a couple hours the lighting on the Sensory Bridge freezes. Other functions still seem to be working (the sweet spot LEDs are moving and I can connect to the device over USB). When I change back to the mast and set the LED settings for the mast it doesn't freeze. Maybe a bug somewhere specific to the output for MicroDose?
> 
> ![IMG_1358](https://private-user-images.githubusercontent.com/315485/306699841-ce4f7768-b0d6-4efb-8056-4079fe75b7e9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzMyMjEsIm5iZiI6MTcwOTE3MjkyMSwicGF0aCI6Ii8zMTU0ODUvMzA2Njk5ODQxLWNlNGY3NzY4LWIwZDYtNGVmYi04MDU2LTQwNzlmZTc1YjdlOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDIxNTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU4MTYxYjBhMDVjMWRhOTMyNmYxZDg2MGYyNWE0NzZmMzU0NTU1YmZmMDNkMWY3M2JhM2U1MTVjZjUyMTJlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.67TdAoAPwUKRfI_0vSk2f7y2rL-pbI7K1jOtSEk_src)

Try setting the LED count to 130 Pixels and see if it still crashes on you. So far it's running longer than usual when using 130 pixel count with the Microdose. 

126 pixel count seemed not crash quick from my quick test also but it does leave 2 leds not working when you do that which is better than crashing but with the 130 pixel setting you get all LED's and so far no crashing. 

Need longer term testing to see if it fixes the issue until the bug is fixed.

**Comment by RWBRWB** [comment]
> The MicroDose looks pretty good. But after a couple hours the lighting on the Sensory Bridge freezes. Other functions still seem to be working (the sweet spot LEDs are moving and I can connect to the device over USB). When I change back to the mast and set the LED settings for the mast it doesn't freeze. Maybe a bug somewhere specific to the output for MicroDose?
> 
> ![IMG_1358](https://private-user-images.githubusercontent.com/315485/306699841-ce4f7768-b0d6-4efb-8056-4079fe75b7e9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNzk4ODAsIm5iZiI6MTcwOTE3OTU4MCwicGF0aCI6Ii8zMTU0ODUvMzA2Njk5ODQxLWNlNGY3NzY4LWIwZDYtNGVmYi04MDU2LTQwNzlmZTc1YjdlOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDQwNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA3N2NkZGFlYmVkM2M0M2Q2YzUyZDE1NWIxMjE2YjIzNWZkZDUyMzIxZjcxOTI2OTlhYmE1N2E2NDVjYjllNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.C5qOqPbSgi-pbWAgFKt2-TNGy2JAvW1_EhK46mFqHV4)

Until it's fixed you can solder the center to 1 pads on the back of the Microdose PCB and then just set the mast to be the regular 128 LED mast and it will work without crashing and to me looks exactly the same even though the refresh rate is lower I guess since your not driving 64 LED's separately anymore. 

You can change it back to dual data line by removing the solder jumper once the code is fixed. 

This will let you enjoy the Microdose without needing to reset it everyday. 

I love these things LOL

**Comment by connornishijima** [comment]
I'm updating to let you guys know that I've started to investigate the MicroDose issue today, hang tight for a fix! It must be something I changed in 4.1.0.

**Comment by connornishijima** [comment]
4.1.1 is out now, which has fixed the LED thread lockup issues!

https://github.com/connornishijima/SensoryBridge/releases/tag/4.1.1

**Comment by andyshinn** [comment]
It is working for longer periods now. But it seems to lock up similarly overnight. I notice the next morning the same behavior where the LEDs do not respond (everything stays off) but I do see the sweet spot LEDs responding to sound.

**Comment by jhermans73** [comment]
Same problem here - sometimes a few hours, occasionally a few days, before lockup.  I guess it's better than the 30 seconds to 10 minutes I was experiencing with 4.1.0.
